spring:
  datasource:
    url: jdbc:mariadb://192.168.0.2:3306/blog
    driver-class-name: org.mariadb.jdbc.Driver
    username: cos
    password: cos1234
#  jpa:
#    open-in-view: false
#    generate-ddl: true
#    show-sql: true
#    hibernate:
#      ddl-auto: update
  
  jpa:
     open-in-view: true
     hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
     show-sql: true
     properties:
        hibernate :
                format_sql:true
 
  jackson:
    serialization:
      fail-on-empty-beans: false
      
  mvc:
   view:
    prefix: /WEB-INF/views/
    suffix: .jsp      
